import type { BasketDefinition, BasketStock } from "@/types/basket";

export const FALLBACK_STOCK_DATA: Record<string, Partial<BasketStock>> = {
  INFY: { name: "Infosys Ltd", currentPrice: 1568.45, change: 23.50, changePercent: 1.52, rsi: 62.4, macd: 12.35, trend: "Strong Trend", confidence: 78 },
  TCS: { name: "Tata Consultancy Services", currentPrice: 3892.10, change: -15.20, changePercent: -0.39, rsi: 48.2, macd: -3.45, trend: "Weak Trend", confidence: 45 },
  HCLTECH: { name: "HCL Technologies Ltd", currentPrice: 1420.60, change: 8.75, changePercent: 0.62, rsi: 55.8, macd: 5.20, trend: "Strong Trend", confidence: 62 },
  WIPRO: { name: "Wipro Ltd", currentPrice: 489.30, change: 6.15, changePercent: 1.27, rsi: 58.6, macd: 4.80, trend: "Strong Trend", confidence: 65 },
  TECHM: { name: "Tech Mahindra Ltd", currentPrice: 1285.00, change: -10.50, changePercent: -0.81, rsi: 42.1, macd: -8.20, trend: "Weak Trend", confidence: 35 },
  LTTS: { name: "L&T Technology Services", currentPrice: 5120.75, change: 45.30, changePercent: 0.89, rsi: 60.3, macd: 15.10, trend: "Strong Trend", confidence: 72 },
  PERSISTENT: { name: "Persistent Systems Ltd", currentPrice: 4850.00, change: 120.50, changePercent: 2.55, rsi: 68.7, macd: 28.40, trend: "Strong Trend", confidence: 85 },
  COFORGE: { name: "Coforge Ltd", currentPrice: 6240.00, change: 38.20, changePercent: 0.62, rsi: 56.4, macd: 10.15, trend: "Strong Trend", confidence: 60 },
  MINDTREE: { name: "LTIMindtree Ltd", currentPrice: 5678.90, change: -22.10, changePercent: -0.39, rsi: 52.8, macd: -2.30, trend: "Weak Trend", confidence: 48 },
  MPHASIS: { name: "Mphasis Ltd", currentPrice: 2456.30, change: 18.40, changePercent: 0.75, rsi: 54.2, macd: 6.80, trend: "Strong Trend", confidence: 58 },
  LTIM: { name: "LTIMindtree Ltd", currentPrice: 5678.90, change: -22.10, changePercent: -0.39, rsi: 52.8, macd: -2.30, trend: "Weak Trend", confidence: 48 },
  RELIANCE: { name: "Reliance Industries Ltd", currentPrice: 2956.20, change: 34.80, changePercent: 1.19, rsi: 61.5, macd: 18.20, trend: "Strong Trend", confidence: 75 },
  BHARTIARTL: { name: "Bharti Airtel Ltd", currentPrice: 1285.60, change: 15.40, changePercent: 1.21, rsi: 63.8, macd: 14.50, trend: "Strong Trend", confidence: 72 },
  LT: { name: "Larsen & Toubro Ltd", currentPrice: 3456.80, change: -12.30, changePercent: -0.35, rsi: 48.5, macd: -4.20, trend: "Weak Trend", confidence: 42 },
  TITAN: { name: "Titan Company Ltd", currentPrice: 3421.50, change: 28.70, changePercent: 0.85, rsi: 57.3, macd: 8.40, trend: "Strong Trend", confidence: 63 },
  HAL: { name: "Hindustan Aeronautics Ltd", currentPrice: 4235.00, change: 85.60, changePercent: 2.06, rsi: 65.2, macd: 22.10, trend: "Strong Trend", confidence: 80 },
  ADANIENT: { name: "Adani Enterprises Ltd", currentPrice: 3120.40, change: -45.20, changePercent: -1.43, rsi: 38.5, macd: -15.30, trend: "Weak Trend", confidence: 28 },
  DLF: { name: "DLF Ltd", currentPrice: 845.60, change: 12.30, changePercent: 1.48, rsi: 59.8, macd: 7.60, trend: "Strong Trend", confidence: 68 },
  SIEMENS: { name: "Siemens Ltd", currentPrice: 6230.00, change: 52.10, changePercent: 0.84, rsi: 55.6, macd: 11.40, trend: "Strong Trend", confidence: 62 },
  BEL: { name: "Bharat Electronics Ltd", currentPrice: 285.40, change: 8.20, changePercent: 2.96, rsi: 66.8, macd: 14.60, trend: "Strong Trend", confidence: 82 },
  TATASTEEL: { name: "Tata Steel Ltd", currentPrice: 165.80, change: -3.40, changePercent: -2.01, rsi: 35.2, macd: -12.80, trend: "Weak Trend", confidence: 22 },
  JSWSTEEL: { name: "JSW Steel Ltd", currentPrice: 892.50, change: -8.60, changePercent: -0.95, rsi: 42.8, macd: -6.50, trend: "Weak Trend", confidence: 32 },
  HINDALCO: { name: "Hindalco Industries Ltd", currentPrice: 678.30, change: 5.40, changePercent: 0.80, rsi: 54.6, macd: 3.80, trend: "Strong Trend", confidence: 55 },
  ADANIPORTS: { name: "Adani Ports & SEZ Ltd", currentPrice: 1345.20, change: 18.50, changePercent: 1.39, rsi: 60.2, macd: 9.30, trend: "Strong Trend", confidence: 70 },
  NTPC: { name: "NTPC Ltd", currentPrice: 362.80, change: 4.60, changePercent: 1.28, rsi: 58.4, macd: 5.60, trend: "Strong Trend", confidence: 64 },
  HDFCBANK: { name: "HDFC Bank Ltd", currentPrice: 1658.40, change: 12.50, changePercent: 0.76, rsi: 56.8, macd: 7.20, trend: "Strong Trend", confidence: 66 },
  ICICIBANK: { name: "ICICI Bank Ltd", currentPrice: 1125.30, change: 8.40, changePercent: 0.75, rsi: 55.2, macd: 6.80, trend: "Strong Trend", confidence: 64 },
  KOTAKBANK: { name: "Kotak Mahindra Bank Ltd", currentPrice: 1782.60, change: -10.20, changePercent: -0.57, rsi: 46.5, macd: -4.50, trend: "Weak Trend", confidence: 40 },
  SBIN: { name: "State Bank of India", currentPrice: 785.40, change: 9.60, changePercent: 1.24, rsi: 59.5, macd: 11.20, trend: "Strong Trend", confidence: 71 },
  AXISBANK: { name: "Axis Bank Ltd", currentPrice: 1120.80, change: -6.30, changePercent: -0.56, rsi: 47.2, macd: -3.80, trend: "Weak Trend", confidence: 38 },
  INDUSINDBK: { name: "IndusInd Bank Ltd", currentPrice: 1452.00, change: 14.50, changePercent: 1.01, rsi: 57.8, macd: 8.90, trend: "Strong Trend", confidence: 62 },
  BANKBARODA: { name: "Bank of Baroda", currentPrice: 268.50, change: 5.20, changePercent: 1.98, rsi: 62.4, macd: 10.50, trend: "Strong Trend", confidence: 76 },
  PNB: { name: "Punjab National Bank", currentPrice: 128.30, change: 2.80, changePercent: 2.23, rsi: 63.8, macd: 8.20, trend: "Strong Trend", confidence: 74 },
  CANBK: { name: "Canara Bank", currentPrice: 118.60, change: 1.90, changePercent: 1.63, rsi: 60.5, macd: 6.40, trend: "Strong Trend", confidence: 68 },
  FEDERALBNK: { name: "Federal Bank Ltd", currentPrice: 182.40, change: 2.60, changePercent: 1.45, rsi: 58.9, macd: 5.80, trend: "Strong Trend", confidence: 65 },
  IDFCFIRSTB: { name: "IDFC First Bank Ltd", currentPrice: 82.60, change: 1.20, changePercent: 1.47, rsi: 59.2, macd: 4.60, trend: "Strong Trend", confidence: 63 },
  RBLBANK: { name: "RBL Bank Ltd", currentPrice: 256.80, change: -4.30, changePercent: -1.65, rsi: 36.8, macd: -9.40, trend: "Weak Trend", confidence: 25 },
  ITC: { name: "ITC Ltd", currentPrice: 468.20, change: 5.80, changePercent: 1.25, rsi: 58.6, macd: 8.10, trend: "Strong Trend", confidence: 67 },
  HINDUNILVR: { name: "Hindustan Unilever Ltd", currentPrice: 2568.40, change: -8.50, changePercent: -0.33, rsi: 48.9, macd: -2.80, trend: "Weak Trend", confidence: 44 },
  NESTLEIND: { name: "Nestlé India Ltd", currentPrice: 2546.70, change: 15.30, changePercent: 0.60, rsi: 54.5, macd: 4.20, trend: "Strong Trend", confidence: 56 },
  ASIANPAINT: { name: "Asian Paints Ltd", currentPrice: 2856.90, change: -18.40, changePercent: -0.64, rsi: 45.8, macd: -6.50, trend: "Weak Trend", confidence: 36 },
  ULTRACEMCO: { name: "UltraTech Cement Ltd", currentPrice: 10450.00, change: 85.60, changePercent: 0.83, rsi: 56.2, macd: 15.80, trend: "Strong Trend", confidence: 62 },
  BAJFINANCE: { name: "Bajaj Finance Ltd", currentPrice: 7120.00, change: 52.30, changePercent: 0.74, rsi: 55.8, macd: 10.40, trend: "Strong Trend", confidence: 60 },
  MARUTI: { name: "Maruti Suzuki India Ltd", currentPrice: 11520.00, change: -45.00, changePercent: -0.39, rsi: 48.6, macd: -5.20, trend: "Weak Trend", confidence: 42 },
  EICHERMOT: { name: "Eicher Motors Ltd", currentPrice: 4568.00, change: 32.40, changePercent: 0.71, rsi: 54.8, macd: 7.60, trend: "Strong Trend", confidence: 58 },
  DRREDDY: { name: "Dr. Reddy's Laboratories Ltd", currentPrice: 6250.00, change: -28.50, changePercent: -0.45, rsi: 47.5, macd: -4.80, trend: "Weak Trend", confidence: 38 },
  SUNPHARMA: { name: "Sun Pharmaceutical Industries Ltd", currentPrice: 1586.40, change: 14.20, changePercent: 0.90, rsi: 57.4, macd: 8.50, trend: "Strong Trend", confidence: 64 },
  TATACONSUM: { name: "Tata Consumer Products Ltd", currentPrice: 1056.80, change: 8.60, changePercent: 0.82, rsi: 55.6, macd: 5.20, trend: "Strong Trend", confidence: 60 },
  BRITANNIA: { name: "Britannia Industries Ltd", currentPrice: 5240.00, change: 22.50, changePercent: 0.43, rsi: 52.8, macd: 3.60, trend: "Strong Trend", confidence: 52 },
  TATAMOTORS: { name: "Tata Motors Ltd", currentPrice: 986.50, change: 12.40, changePercent: 1.27, rsi: 60.2, macd: 9.80, trend: "Strong Trend", confidence: 72 },
  HEROMOTOCO: { name: "Hero MotoCorp Ltd", currentPrice: 4856.00, change: -18.30, changePercent: -0.38, rsi: 48.2, macd: -3.50, trend: "Weak Trend", confidence: 42 },
  ASHOKLEY: { name: "Ashok Leyland Ltd", currentPrice: 228.50, change: 4.80, changePercent: 2.15, rsi: 64.2, macd: 8.40, trend: "Strong Trend", confidence: 78 },
  BALKRISIND: { name: "Balkrishna Industries Ltd", currentPrice: 2850.00, change: 18.50, changePercent: 0.65, rsi: 54.2, macd: 5.80, trend: "Strong Trend", confidence: 56 },
  TVSMOTOR: { name: "TVS Motor Company Ltd", currentPrice: 2245.60, change: 28.40, changePercent: 1.28, rsi: 61.5, macd: 12.60, trend: "Strong Trend", confidence: 74 },
  MOTHERSUMI: { name: "Motherson Sumi Wiring India Ltd", currentPrice: 68.40, change: 1.20, changePercent: 1.79, rsi: 60.8, macd: 4.20, trend: "Strong Trend", confidence: 66 },
  CIPLA: { name: "Cipla Ltd", currentPrice: 1425.80, change: 10.40, changePercent: 0.73, rsi: 55.4, macd: 6.80, trend: "Strong Trend", confidence: 60 },
  DIVISLAB: { name: "Divi's Laboratories Ltd", currentPrice: 3956.20, change: -22.40, changePercent: -0.56, rsi: 46.8, macd: -5.60, trend: "Weak Trend", confidence: 38 },
  AUROPHARMA: { name: "Aurobindo Pharma Ltd", currentPrice: 1125.00, change: 12.80, changePercent: 1.15, rsi: 58.9, macd: 7.40, trend: "Strong Trend", confidence: 66 },
  LUPIN: { name: "Lupin Ltd", currentPrice: 1580.00, change: 8.60, changePercent: 0.55, rsi: 52.6, macd: 4.20, trend: "Strong Trend", confidence: 54 },
  BIOCON: { name: "Biocon Ltd", currentPrice: 312.40, change: -5.80, changePercent: -1.82, rsi: 34.5, macd: -11.20, trend: "Weak Trend", confidence: 20 },
  TORNTPHARM: { name: "Torrent Pharmaceuticals Ltd", currentPrice: 2640.00, change: 18.50, changePercent: 0.71, rsi: 55.2, macd: 8.10, trend: "Strong Trend", confidence: 62 },
  ALKEM: { name: "Alkem Laboratories Ltd", currentPrice: 4980.00, change: 32.40, changePercent: 0.65, rsi: 54.6, macd: 9.20, trend: "Strong Trend", confidence: 58 },
  PFIZER: { name: "Pfizer Ltd", currentPrice: 4580.00, change: -15.20, changePercent: -0.33, rsi: 48.5, macd: -2.60, trend: "Weak Trend", confidence: 44 },
  CADILAHC: { name: "Cadila Healthcare Ltd (Zydus)", currentPrice: 685.60, change: 5.40, changePercent: 0.79, rsi: 55.8, macd: 4.60, trend: "Strong Trend", confidence: 58 },
  ONGC: { name: "Oil & Natural Gas Corporation Ltd", currentPrice: 268.50, change: 3.20, changePercent: 1.21, rsi: 58.5, macd: 5.80, trend: "Strong Trend", confidence: 64 },
  IOC: { name: "Indian Oil Corporation Ltd", currentPrice: 168.40, change: 2.60, changePercent: 1.57, rsi: 60.2, macd: 4.50, trend: "Strong Trend", confidence: 68 },
  BPCL: { name: "Bharat Petroleum Corporation Ltd", currentPrice: 615.30, change: 8.40, changePercent: 1.38, rsi: 59.8, macd: 7.20, trend: "Strong Trend", confidence: 66 },
  GAIL: { name: "GAIL (India) Ltd", currentPrice: 205.60, change: 3.80, changePercent: 1.88, rsi: 62.4, macd: 6.80, trend: "Strong Trend", confidence: 72 },
  POWERGRID: { name: "Power Grid Corporation of India Ltd", currentPrice: 328.50, change: 4.20, changePercent: 1.29, rsi: 58.6, macd: 5.40, trend: "Strong Trend", confidence: 64 },
  ADANIGREEN: { name: "Adani Green Energy Ltd", currentPrice: 1856.40, change: 25.60, changePercent: 1.40, rsi: 60.5, macd: 15.20, trend: "Strong Trend", confidence: 72 },
  TATAPOWER: { name: "Tata Power Company Ltd", currentPrice: 428.60, change: 6.80, changePercent: 1.61, rsi: 61.2, macd: 8.60, trend: "Strong Trend", confidence: 70 },
  COALINDIA: { name: "Coal India Ltd", currentPrice: 465.30, change: -4.20, changePercent: -0.89, rsi: 44.5, macd: -5.80, trend: "Weak Trend", confidence: 34 },
  HINDPETRO: { name: "Hindustan Petroleum Corporation Ltd", currentPrice: 528.40, change: 6.20, changePercent: 1.19, rsi: 58.2, macd: 5.60, trend: "Strong Trend", confidence: 65 },
};

export const BASKET_DEFINITIONS: BasketDefinition[] = [
  {
    id: "ai-growth",
    name: "AI Growth Basket",
    description:
      "Companies leading in AI and digital transformation with strong technical momentum",
    sector: "Technology",
    symbols: [
      "INFY",
      "TCS",
      "HCLTECH",
      "WIPRO",
      "TECHM",
      "LTTS",
      "PERSISTENT",
      "COFORGE",
      "MINDTREE",
      "MPHASIS",
    ],
  },
  {
    id: "momentum",
    name: "Momentum Basket",
    description:
      "Stocks with highest recent price momentum, volume strength, and technical trend scores",
    sector: "Multi-Sector",
    symbols: [
      "RELIANCE",
      "BHARTIARTL",
      "LT",
      "TITAN",
      "HAL",
      "ADANIENT",
      "DLF",
      "SIEMENS",
      "BEL",
      "TATASTEEL",
      "JSWSTEEL",
      "HINDALCO",
      "ADANIPORTS",
      "NTPC",
    ],
  },
  {
    id: "strong-buy",
    name: "Strong Buy Basket",
    description:
      "High-conviction BUY signals identified by our multi-factor analysis engine",
    sector: "Multi-Sector",
    symbols: [
      "HDFCBANK",
      "ICICIBANK",
      "KOTAKBANK",
      "ITC",
      "HINDUNILVR",
      "NESTLEIND",
      "ASIANPAINT",
      "ULTRACEMCO",
      "BAJFINANCE",
      "MARUTI",
      "EICHERMOT",
      "DRREDDY",
      "SUNPHARMA",
      "TATACONSUM",
      "BRITANNIA",
    ],
  },
  {
    id: "banking",
    name: "Banking Basket",
    description: "Leading Indian banking and financial services institutions",
    sector: "Financial Services",
    symbols: [
      "HDFCBANK",
      "ICICIBANK",
      "SBIN",
      "KOTAKBANK",
      "AXISBANK",
      "INDUSINDBK",
      "BANKBARODA",
      "PNB",
      "CANBK",
      "FEDERALBNK",
      "IDFCFIRSTB",
      "RBLBANK",
    ],
  },
  {
    id: "it",
    name: "IT Basket",
    description:
      "Top Indian information technology and software services companies",
    sector: "Information Technology",
    symbols: [
      "TCS",
      "INFY",
      "HCLTECH",
      "WIPRO",
      "TECHM",
      "LTTS",
      "PERSISTENT",
      "COFORGE",
      "MINDTREE",
      "MPHASIS",
      "LTIM",
    ],
  },
  {
    id: "auto",
    name: "Auto Basket",
    description:
      "Major automobile manufacturers and auto component leaders",
    sector: "Automobile",
    symbols: [
      "MARUTI",
      "TATAMOTORS",
      "EICHERMOT",
      "HEROMOTOCO",
      "ASHOKLEY",
      "BALKRISIND",
      "TVSMOTOR",
      "MOTHERSUMI",
    ],
  },
  {
    id: "pharma",
    name: "Pharma Basket",
    description:
      "Leading pharmaceutical and healthcare companies driving innovation",
    sector: "Pharmaceuticals",
    symbols: [
      "SUNPHARMA",
      "DRREDDY",
      "CIPLA",
      "DIVISLAB",
      "AUROPHARMA",
      "LUPIN",
      "BIOCON",
      "TORNTPHARM",
      "ALKEM",
      "PFIZER",
      "CADILAHC",
    ],
  },
  {
    id: "energy",
    name: "Energy Basket",
    description:
      "Key players in oil, gas, power, and renewable energy sectors",
    sector: "Energy",
    symbols: [
      "RELIANCE",
      "ONGC",
      "IOC",
      "BPCL",
      "GAIL",
      "NTPC",
      "POWERGRID",
      "ADANIGREEN",
      "TATAPOWER",
      "COALINDIA",
      "HINDPETRO",
    ],
  },
];
